version: "4.21.1"
services:
  django:
    container_name: Django
    restart: always
    build:
      context: ./backend
    volumes:
      - ./backend:/usr/src/backend
    command:
      - python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
