# Generated by Django 4.2 on 2023-06-23 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(help_text='format:max-255,required', max_length=255, verbose_name='Title'),
        ),
    ]
