# Generated by Django 4.2.2 on 2023-07-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_category_parent_alter_ticket_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='color',
            field=models.CharField(default='#fdfdfd', help_text='format: max-20, rgba,hex ,mui color palette like primary, secondary and can use main,light and dark', max_length=50, verbose_name='Color'),
        ),
    ]
